/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewEditWorkspace.java
 *
 * Created on 2010-1-16, 9:27:28
 */

package com.jotov.versia.gui;

import javax.swing.JFrame;
import org.jdesktop.application.Action;

/**
 *
 * @author v
 */
public class NewEditWorkspace extends javax.swing.JDialog {
    private String actionCommand;

    /** Creates new form NewEditWorkspace */
    public NewEditWorkspace(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
    }
    public NewEditWorkspace(java.awt.Frame parent, String strWorkspaceName) {
        super(parent, true);
        initComponents();
        jtfWorkspaceName.setText(strWorkspaceName);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfWorkspaceName = new javax.swing.JTextField();
        jbSave = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(desktopapplication1.DesktopApplication1.class).getContext().getResourceMap(NewEditWorkspace.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jtfWorkspaceName.setText(resourceMap.getString("jtfWorkspaceName.text")); // NOI18N
        jtfWorkspaceName.setName("jtfWorkspaceName"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(desktopapplication1.DesktopApplication1.class).getContext().getActionMap(NewEditWorkspace.class, this);
        jbSave.setAction(actionMap.get("doSave")); // NOI18N
        jbSave.setText(resourceMap.getString("jbSave.text")); // NOI18N
        jbSave.setActionCommand(resourceMap.getString("jbSave.actionCommand")); // NOI18N
        jbSave.setName("jbSave"); // NOI18N

        jbCancel.setAction(actionMap.get("doCancel")); // NOI18N
        jbCancel.setText(resourceMap.getString("jbCancel.text")); // NOI18N
        jbCancel.setActionCommand(resourceMap.getString("jbCancel.actionCommand")); // NOI18N
        jbCancel.setName("jbCancel"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jtfWorkspaceName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jbCancel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jbSave, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jbSave)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel1)
                        .add(jtfWorkspaceName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jbCancel)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void doSave() {
        actionCommand = jbSave.getActionCommand();
        dispose();
    }

    @Action
    public void doCancel() {
        actionCommand = jbCancel.getActionCommand();
        dispose();
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbSave;
    private javax.swing.JTextField jtfWorkspaceName;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the actionCommand
     */
    public String getActionCommand() {
        return actionCommand;
    }
    public String getWSName() {
        return jtfWorkspaceName.getText();
    }

}
