REM INSERTING into VERSION_GRAPH
Insert into VERSION_GRAPH (VO_ID,SOURCE_VP_ID,TARGET_VP_ID,USER_ID,ARC_ID) values (2,1,2,null,1);
Insert into VERSION_GRAPH (VO_ID,SOURCE_VP_ID,TARGET_VP_ID,USER_ID,ARC_ID) values (2,2,3,null,2);
Insert into VERSION_GRAPH (VO_ID,SOURCE_VP_ID,TARGET_VP_ID,USER_ID,ARC_ID) values (2,1,3,null,3);
Insert into VERSION_GRAPH (VO_ID,SOURCE_VP_ID,TARGET_VP_ID,USER_ID,ARC_ID) values (2,3,4,null,4);
Insert into VERSION_GRAPH (VO_ID,SOURCE_VP_ID,TARGET_VP_ID,USER_ID,ARC_ID) values (2,3,5,null,5);
