/*
 * DesktopApplication1View.java
 */
package desktopapplication1;

import com.jotov.versia.WorkEnvironment;
import com.jotov.versia.gui.VersiaAboutBox;
import com.jotov.versia.json.JSONConnection;
import com.jotov.versia.gui.OpenWorkspace;
import com.jotov.versia.gui2.command.CommandFactory;
import com.jotov.versia.gui2.command.ICommand;
import com.jotov.versia.voInfo;
import com.jotov.versia.workitemInfo;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.application.Action;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

// Variables declaration - do not modify
/***********************************************************************
 * Module:  DesktopApplication1View.java
 * Author:  Vladimir Jotov
 * Purpose: Defines the Class DesktopApplication1View
 ***********************************************************************/
public class DesktopApplication1View extends FrameView {

    private WorkEnvironment workEnvironment;
    //private int uid = 1;
    DefaultMutableTreeNode voRoot, wiAttachedRoot, wiAvailableRoot;
    DefaultTreeModel voModel, wiAttachedModel, wiAvailableModel;

    public DesktopApplication1View(SingleFrameApplication app) {
        super(app);

        workEnvironment = WorkEnvironment.getWorkEnvironment();

        voRoot = new DefaultMutableTreeNode();
        wiAttachedRoot = new DefaultMutableTreeNode();
        wiAvailableRoot = new DefaultMutableTreeNode();
        voModel = new DefaultTreeModel(voRoot);
        wiAttachedModel = new DefaultTreeModel(wiAttachedRoot);
        wiAvailableModel = new DefaultTreeModel(wiAvailableRoot);

        initComponents();

    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = DesktopApplication1.getApplication().getMainFrame();
            aboutBox = new VersiaAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        DesktopApplication1.getApplication().show(aboutBox);
    }

    @Action
    public void showOpenProduct() {
        if (openProduct == null) {
            JFrame mainFrame = DesktopApplication1.getApplication().getMainFrame();
            openProduct = new OpenWorkspace(mainFrame);
            openProduct.setLocationRelativeTo(mainFrame);
            openProduct.setTitle("Open Product&Release");
        }
        DesktopApplication1.getApplication().show(openProduct);
        if (openProduct.getActionCommand().equals("BTN_OK")) {
            workEnvironment.openEnvironment();
            loadVersionedObjects();
            loadWorkItems();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jpWorkspaces = new javax.swing.JPanel();
        jpWorkItems = new javax.swing.JPanel();
        jlAttachedWorkitems = new javax.swing.JLabel();
        jspAttachedWorkItems = new javax.swing.JScrollPane();
        jtAttachedWorkItems = new javax.swing.JTree();
        jbAttachWI = new javax.swing.JButton();
        jbDetachWI = new javax.swing.JButton();
        jbCreateWI = new javax.swing.JButton();
        jlAvailableWorkitems = new javax.swing.JLabel();
        jspAvailableWorkItems = new javax.swing.JScrollPane();
        jtAvailableWorkItems = new javax.swing.JTree();
        jpCommands = new javax.swing.JPanel();
        jbCreateVO = new javax.swing.JButton();
        jbSaveVO = new javax.swing.JButton();
        jbChangeVOHat = new javax.swing.JButton();
        jbPublishVO = new javax.swing.JButton();
        jbPutBackVO = new javax.swing.JButton();
        jbViewVOHistory = new javax.swing.JButton();
        jbViewVODistribution = new javax.swing.JButton();
        jpVersionedObjects = new javax.swing.JPanel();
        jlVersionedObjects = new javax.swing.JLabel();
        jspVersionedObjects = new javax.swing.JScrollPane();
        jtVOs = new javax.swing.JTree();
        jlVersionedObject = new javax.swing.JLabel();
        jtfVOName = new javax.swing.JTextField();
        jspVODatum = new javax.swing.JScrollPane();
        jtaVODatum = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        jmiLogin = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmiOpenProduct = new javax.swing.JMenuItem();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        usersMenu = new javax.swing.JMenu();
        jmiManageUser = new javax.swing.JMenuItem();
        jmiPermitions = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();

        mainPanel.setName("mainPanel"); // NOI18N

        jpWorkspaces.setEnabled(false);
        jpWorkspaces.setMinimumSize(new java.awt.Dimension(847, 508));
        jpWorkspaces.setName("jpWorkspaces"); // NOI18N
        jpWorkspaces.setPreferredSize(new java.awt.Dimension(847, 508));

        jpWorkItems.setMinimumSize(new java.awt.Dimension(300, 100));
        jpWorkItems.setName("jpWorkItems"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(desktopapplication1.DesktopApplication1.class).getContext().getResourceMap(DesktopApplication1View.class);
        jlAttachedWorkitems.setText(resourceMap.getString("jlAttachedWorkitems.text")); // NOI18N
        jlAttachedWorkitems.setName("jlAttachedWorkitems"); // NOI18N

        jspAttachedWorkItems.setName("jspAttachedWorkItems"); // NOI18N

        jtAttachedWorkItems.setModel(wiAttachedModel);
        jtAttachedWorkItems.setMinimumSize(new java.awt.Dimension(100, 50));
        jtAttachedWorkItems.setName("jtAttachedWorkItems"); // NOI18N
        jtAttachedWorkItems.setPreferredSize(new java.awt.Dimension(100, 50));
        jtAttachedWorkItems.setRootVisible(false);
        jtAttachedWorkItems.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jtAttachedWorkItemsValueChanged(evt);
            }
        });
        jspAttachedWorkItems.setViewportView(jtAttachedWorkItems);

        jbAttachWI.setText(resourceMap.getString("jbAttachWI.text")); // NOI18N
        jbAttachWI.setEnabled(false);
        jbAttachWI.setName("jbAttachWI"); // NOI18N
        jbAttachWI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAttachWIActionPerformed(evt);
            }
        });

        jbDetachWI.setText(resourceMap.getString("jbDetachWI.text")); // NOI18N
        jbDetachWI.setEnabled(false);
        jbDetachWI.setName("jbDetachWI"); // NOI18N
        jbDetachWI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDetachWIActionPerformed(evt);
            }
        });

        jbCreateWI.setText(resourceMap.getString("jbCreateWI.text")); // NOI18N
        jbCreateWI.setEnabled(false);
        jbCreateWI.setName("jbCreateWI"); // NOI18N

        jlAvailableWorkitems.setText(resourceMap.getString("jlAvailableWorkitems.text")); // NOI18N
        jlAvailableWorkitems.setName("jlAvailableWorkitems"); // NOI18N

        jspAvailableWorkItems.setName("jspAvailableWorkItems"); // NOI18N

        jtAvailableWorkItems.setModel(wiAvailableModel);
        jtAvailableWorkItems.setName("jtAvailableWorkItems"); // NOI18N
        jtAvailableWorkItems.setRootVisible(false);
        jtAvailableWorkItems.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jtAvailableWorkItemsValueChanged(evt);
            }
        });
        jspAvailableWorkItems.setViewportView(jtAvailableWorkItems);

        org.jdesktop.layout.GroupLayout jpWorkItemsLayout = new org.jdesktop.layout.GroupLayout(jpWorkItems);
        jpWorkItems.setLayout(jpWorkItemsLayout);
        jpWorkItemsLayout.setHorizontalGroup(
            jpWorkItemsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpWorkItemsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpWorkItemsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpWorkItemsLayout.createSequentialGroup()
                        .add(jspAttachedWorkItems, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 214, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jpWorkItemsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jbCreateWI, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jbDetachWI)
                            .add(jbAttachWI)))
                    .add(jlAttachedWorkitems))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jpWorkItemsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jlAvailableWorkitems)
                    .add(jspAvailableWorkItems, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jpWorkItemsLayout.linkSize(new java.awt.Component[] {jspAttachedWorkItems, jspAvailableWorkItems}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jpWorkItemsLayout.linkSize(new java.awt.Component[] {jbAttachWI, jbCreateWI, jbDetachWI}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jpWorkItemsLayout.setVerticalGroup(
            jpWorkItemsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpWorkItemsLayout.createSequentialGroup()
                .add(11, 11, 11)
                .add(jpWorkItemsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlAttachedWorkitems, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlAvailableWorkitems, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(jpWorkItemsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jspAvailableWorkItems, 0, 0, Short.MAX_VALUE)
                    .add(jpWorkItemsLayout.createSequentialGroup()
                        .add(jbAttachWI)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbDetachWI)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbCreateWI))
                    .add(jspAttachedWorkItems, 0, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpCommands.setName("jpCommands"); // NOI18N

        jbCreateVO.setText(resourceMap.getString("jbCreateVO.text")); // NOI18N
        jbCreateVO.setEnabled(false);
        jbCreateVO.setName("jbCreateVO"); // NOI18N

        jbSaveVO.setText(resourceMap.getString("jbSaveVO.text")); // NOI18N
        jbSaveVO.setEnabled(false);
        jbSaveVO.setName("jbSaveVO"); // NOI18N
        jbSaveVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveVOActionPerformed(evt);
            }
        });

        jbChangeVOHat.setText(resourceMap.getString("jbChangeVOHat.text")); // NOI18N
        jbChangeVOHat.setEnabled(false);
        jbChangeVOHat.setName("jbChangeVOHat"); // NOI18N
        jbChangeVOHat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbChangeVOHatActionPerformed(evt);
            }
        });

        jbPublishVO.setText(resourceMap.getString("jbPublishVO.text")); // NOI18N
        jbPublishVO.setEnabled(false);
        jbPublishVO.setName("jbPublishVO"); // NOI18N
        jbPublishVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPublishVOActionPerformed(evt);
            }
        });

        jbPutBackVO.setText(resourceMap.getString("jbPutBackVO.text")); // NOI18N
        jbPutBackVO.setEnabled(false);
        jbPutBackVO.setName("jbPutBackVO"); // NOI18N
        jbPutBackVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPutBackVOActionPerformed(evt);
            }
        });

        jbViewVOHistory.setText(resourceMap.getString("jbViewVOHistory.text")); // NOI18N
        jbViewVOHistory.setEnabled(false);
        jbViewVOHistory.setName("jbViewVOHistory"); // NOI18N
        jbViewVOHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbViewVOHistoryActionPerformed(evt);
            }
        });

        jbViewVODistribution.setText(resourceMap.getString("jbViewVODistribution.text")); // NOI18N
        jbViewVODistribution.setActionCommand(resourceMap.getString("jbViewVODistribution.actionCommand")); // NOI18N
        jbViewVODistribution.setEnabled(false);
        jbViewVODistribution.setName("jbViewVODistribution"); // NOI18N
        jbViewVODistribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbViewVODistributionActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jpCommandsLayout = new org.jdesktop.layout.GroupLayout(jpCommands);
        jpCommands.setLayout(jpCommandsLayout);
        jpCommandsLayout.setHorizontalGroup(
            jpCommandsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpCommandsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jbCreateVO)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jbSaveVO)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jbChangeVOHat)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jbPublishVO)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jbPutBackVO)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jbViewVODistribution)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jbViewVOHistory)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jpCommandsLayout.linkSize(new java.awt.Component[] {jbChangeVOHat, jbCreateVO, jbPublishVO, jbPutBackVO, jbSaveVO, jbViewVODistribution, jbViewVOHistory}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jpCommandsLayout.setVerticalGroup(
            jpCommandsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpCommandsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpCommandsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbCreateVO, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, Short.MAX_VALUE)
                    .add(jbSaveVO, 0, 0, Short.MAX_VALUE)
                    .add(jbChangeVOHat, 0, 0, Short.MAX_VALUE)
                    .add(jbPublishVO, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, Short.MAX_VALUE)
                    .add(jbPutBackVO, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jbViewVODistribution, 0, 0, Short.MAX_VALUE)
                    .add(jbViewVOHistory, 0, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpCommandsLayout.linkSize(new java.awt.Component[] {jbChangeVOHat, jbCreateVO, jbPublishVO, jbPutBackVO, jbSaveVO, jbViewVODistribution, jbViewVOHistory}, org.jdesktop.layout.GroupLayout.VERTICAL);

        jpVersionedObjects.setName("jpVersionedObjects"); // NOI18N

        jlVersionedObjects.setText(resourceMap.getString("jlVersionedObjects.text")); // NOI18N
        jlVersionedObjects.setName("jlVersionedObjects"); // NOI18N

        jspVersionedObjects.setName("jspVersionedObjects"); // NOI18N

        jtVOs.setModel(voModel);
        jtVOs.setName("jtVOs"); // NOI18N
        jtVOs.setRootVisible(false);
        jtVOs.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jtVOsValueChanged(evt);
            }
        });
        jspVersionedObjects.setViewportView(jtVOs);

        jlVersionedObject.setText(resourceMap.getString("jlVersionedObject.text")); // NOI18N
        jlVersionedObject.setName("jlVersionedObject"); // NOI18N

        jtfVOName.setText(resourceMap.getString("jtfVOName.text")); // NOI18N
        jtfVOName.setName("jtfVOName"); // NOI18N

        jspVODatum.setName("jspVODatum"); // NOI18N

        jtaVODatum.setColumns(20);
        jtaVODatum.setRows(5);
        jtaVODatum.setName("jtaVODatum"); // NOI18N
        jspVODatum.setViewportView(jtaVODatum);

        org.jdesktop.layout.GroupLayout jpVersionedObjectsLayout = new org.jdesktop.layout.GroupLayout(jpVersionedObjects);
        jpVersionedObjects.setLayout(jpVersionedObjectsLayout);
        jpVersionedObjectsLayout.setHorizontalGroup(
            jpVersionedObjectsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpVersionedObjectsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpVersionedObjectsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpVersionedObjectsLayout.createSequentialGroup()
                        .add(jlVersionedObjects)
                        .add(85, 85, 85)
                        .add(jlVersionedObject)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jtfVOName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jpVersionedObjectsLayout.createSequentialGroup()
                        .add(jspVersionedObjects, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 172, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jspVODatum, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1718, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpVersionedObjectsLayout.setVerticalGroup(
            jpVersionedObjectsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpVersionedObjectsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpVersionedObjectsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlVersionedObjects)
                    .add(jlVersionedObject)
                    .add(jtfVOName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jpVersionedObjectsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jspVODatum, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .add(jspVersionedObjects, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout jpWorkspacesLayout = new org.jdesktop.layout.GroupLayout(jpWorkspaces);
        jpWorkspaces.setLayout(jpWorkspacesLayout);
        jpWorkspacesLayout.setHorizontalGroup(
            jpWorkspacesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpWorkspacesLayout.createSequentialGroup()
                .add(jpWorkspacesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jpVersionedObjects, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jpWorkspacesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jpWorkItems, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jpCommands, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpWorkspacesLayout.setVerticalGroup(
            jpWorkspacesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpWorkspacesLayout.createSequentialGroup()
                .add(jpWorkItems, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jpCommands, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jpVersionedObjects, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout mainPanelLayout = new org.jdesktop.layout.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpWorkspaces, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1926, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpWorkspaces, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        jmiLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jmiLogin.setActionCommand(resourceMap.getString("jmiLogin.actionCommand")); // NOI18N
        jmiLogin.setEnabled(false);
        jmiLogin.setLabel(resourceMap.getString("jmiLogin.label")); // NOI18N
        jmiLogin.setName("jmiLogin"); // NOI18N
        fileMenu.add(jmiLogin);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setActionCommand(resourceMap.getString("jmiNewProduct.actionCommand")); // NOI18N
        jMenuItem1.setLabel(resourceMap.getString("jmiNewProduct.label")); // NOI18N
        jMenuItem1.setName("jmiNewProduct"); // NOI18N
        fileMenu.add(jMenuItem1);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(desktopapplication1.DesktopApplication1.class).getContext().getActionMap(DesktopApplication1View.class, this);
        jmiOpenProduct.setAction(actionMap.get("showOpenProduct")); // NOI18N
        jmiOpenProduct.setText(resourceMap.getString("jmiOpenProduct.text")); // NOI18N
        jmiOpenProduct.setName("jmiOpenProduct"); // NOI18N
        fileMenu.add(jmiOpenProduct);

        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        usersMenu.setEnabled(false);
        usersMenu.setLabel(resourceMap.getString("usersMenu.label")); // NOI18N
        usersMenu.setName("usersMenu"); // NOI18N

        jmiManageUser.setEnabled(false);
        jmiManageUser.setLabel(resourceMap.getString("jmiManageUser.label")); // NOI18N
        jmiManageUser.setName("jmiManageUser"); // NOI18N
        usersMenu.add(jmiManageUser);

        jmiPermitions.setEnabled(false);
        jmiPermitions.setLabel(resourceMap.getString("jmiPermitions.label")); // NOI18N
        jmiPermitions.setName("jmiPermitions"); // NOI18N
        usersMenu.add(jmiPermitions);

        menuBar.add(usersMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setComponent(jpWorkspaces);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    private void jbAttachWIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAttachWIActionPerformed
        // TODO add your handling code here:
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) jtAvailableWorkItems.getLastSelectedPathComponent();
        if (node != null) {
            try {
                CommandFactory cf = new CommandFactory();
                ICommand cmd = cf.createCommand(CommandFactory.CmdCode.ATTACH_WORK_ITEM);

                HashMap params = new HashMap();
                workitemInfo wiInfo = (workitemInfo) node.getUserObject();
                params.put("wi_id", wiInfo.getWi_id());
                cmd.setParameters(params);
                Integer res = (Integer) cmd.doRequest();
                if (res != null) {
                    loadWorkItems();
                }
            } catch (JSONException ex) {
                Logger.getLogger(DesktopApplication1View.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbAttachWIActionPerformed

    private void jbDetachWIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDetachWIActionPerformed
        // TODO add your handling code here:
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) jtAttachedWorkItems.getLastSelectedPathComponent();
        if (node != null) {
            try {
                CommandFactory cf = new CommandFactory();
                ICommand cmd = cf.createCommand(CommandFactory.CmdCode.DETACH_WORK_ITEM);

                HashMap params = new HashMap();
                workitemInfo wiInfo = (workitemInfo) node.getUserObject();
                params.put("wi_id", wiInfo.getWi_id());
                cmd.setParameters(params);
                Integer res = (Integer) cmd.doRequest();
                if (res != null) {
                    loadWorkItems();
                }
            } catch (JSONException ex) {
                Logger.getLogger(DesktopApplication1View.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbDetachWIActionPerformed

    private void jbSaveVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveVOActionPerformed
        // TODO add your handling code here:
        Map params = new HashMap();

        params.put("vo_name", jtfVOName.getText());
        params.put("vo_datum", jtaVODatum.getText());

        try {
            CommandFactory cf = new CommandFactory();
            ICommand cmd = cf.createCommand(CommandFactory.CmdCode.SAVE_VERSIONED_OBJECT);

            JSONArray vo_ls = (JSONArray) cmd.doRequest();
            if (vo_ls != null) {
                loadVersionedObjects();
            }
        } catch (JSONException ex) {
            Logger.getLogger(DesktopApplication1View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbSaveVOActionPerformed

    private void jbPublishVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPublishVOActionPerformed
        // TODO add your handling code here:
        try {
            CommandFactory cf = new CommandFactory();
            ICommand cmd = cf.createCommand(CommandFactory.CmdCode.PUBLISH_VERSIONED_BJECT);

            Integer int_val = (Integer) cmd.doRequest();
            if (int_val != null) {
                loadVersionedObjects();
            }
        } catch (JSONException ex) {
            Logger.getLogger(DesktopApplication1View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbPublishVOActionPerformed

    private void jbPutBackVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPutBackVOActionPerformed
        // TODO add your handling code here:
        try {
            CommandFactory cf = new CommandFactory();
            ICommand cmd = cf.createCommand(CommandFactory.CmdCode.PUT_BACK_VERSIONED_OBJECT);

            Integer int_val = (Integer) cmd.doRequest();
            if (int_val != null) {
                loadVersionedObjects();
            }
        } catch (JSONException ex) {
            Logger.getLogger(DesktopApplication1View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbPutBackVOActionPerformed

    private void jbViewVODistributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbViewVODistributionActionPerformed
        // TODO add your handling code here:
        //@todo - to show in new dialog versioned object distribution among workspaces of the release.
//        try {
//            JSONConnection jc = new JSONConnection();
//            Map params = new HashMap();
//
//            params.put("vo_id", workEnvironment.getCurrentVersionedObjectID());
//            params.put("release_id", workEnvironment.getRelease());
//
//            jc.prepareJSONRequest("viewVersionedObjectDistribution", params, uid);
//            JSONObject jResponce = jc.doRequest(null);
//            JSONObject err = jResponce.getJSONObject("error");
//            JSONArray Distribution = jResponce.getJSONArray("result");
//            int code = err.getInt("code");
//            if (code != 0) {
//                System.err.println("JSON ERROR loadReleases - code:" + code + "; message:" + err.get("message").toString());
//            }
//            diplayVersionedObjectsDistribution(Distribution);
//        } catch (JSONException ex) {
//            Logger.getLogger(DesktopApplication1View.class.getName()).log(Level.SEVERE, null, ex);
//        }
        //refreshVOButtons(true);
    }//GEN-LAST:event_jbViewVODistributionActionPerformed

    private void jbViewVOHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbViewVOHistoryActionPerformed
        // TODO add your handling code here:
        //@todo - to show in new dialog versioned object distribution among workspaces of the release.
//        try {
//            JSONConnection jc = new JSONConnection();
//            Map params = new HashMap();
//
//            params.put("vo_id", workEnvironment.getCurrentVersionedObjectID());
//            params.put("release_id", workEnvironment.getRelease());
//
//            jc.prepareJSONRequest("viewVersionedObjectHistory", params, uid);
//            JSONObject jResponce = jc.doRequest(null);
//            JSONObject err = jResponce.getJSONObject("error");
//            JSONArray HistoryItems = jResponce.getJSONArray("result");
//            int code = err.getInt("code");
//            if (code != 0) {
//                System.err.println("JSON ERROR loadReleases - code:" + code + "; message:" + err.get("message").toString());
//            }
//            diplayVersionedObjectsHistory(HistoryItems);
//        } catch (JSONException ex) {
//            Logger.getLogger(DesktopApplication1View.class.getName()).log(Level.SEVERE, null, ex);
//        }
        //refreshVOButtons(true);
    }//GEN-LAST:event_jbViewVOHistoryActionPerformed

    private void jtVOsValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jtVOsValueChanged
        // TODO add your handling code here:
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) jtVOs.getLastSelectedPathComponent();
        if (node == null) {
            clearVOData();
        } else {
            //WorkEnvironment we = WorkEnvironment.getWorkEnvironment();
            voInfo nodeInfo = (voInfo) node.getUserObject();
            try {
                workEnvironment.setCurrentVersionedObject(nodeInfo.getVo_id());
            } catch (JSONException ex) {
                Logger.getLogger(DesktopApplication1View.class.getName()).log(Level.SEVERE, null, ex);
            }
            displayVOdata();
        }
    }//GEN-LAST:event_jtVOsValueChanged

    private void jbChangeVOHatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbChangeVOHatActionPerformed
        // TODO add your handling code here:
        //@todo to make functionality - to open new dialog for selection of hat object
    }//GEN-LAST:event_jbChangeVOHatActionPerformed

    private void jtAvailableWorkItemsValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jtAvailableWorkItemsValueChanged
        // TODO add your handling code here:
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) jtAvailableWorkItems.getLastSelectedPathComponent();
        if (node == null) {
            jbAttachWI.setEnabled(false);
            jbDetachWI.setEnabled(false);
        } else {
            jbAttachWI.setEnabled(true);
            jbDetachWI.setEnabled(false);
        }
    }//GEN-LAST:event_jtAvailableWorkItemsValueChanged

    private void jtAttachedWorkItemsValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jtAttachedWorkItemsValueChanged
        // TODO add your handling code here:
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) jtAttachedWorkItems.getLastSelectedPathComponent();
        if (node == null) {
            jbAttachWI.setEnabled(false);
            jbDetachWI.setEnabled(false);
        } else {
            jbAttachWI.setEnabled(false);
            jbDetachWI.setEnabled(true);
        }
    }//GEN-LAST:event_jtAttachedWorkItemsValueChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton jbAttachWI;
    private javax.swing.JButton jbChangeVOHat;
    private javax.swing.JButton jbCreateVO;
    private javax.swing.JButton jbCreateWI;
    private javax.swing.JButton jbDetachWI;
    private javax.swing.JButton jbPublishVO;
    private javax.swing.JButton jbPutBackVO;
    private javax.swing.JButton jbSaveVO;
    private javax.swing.JButton jbViewVODistribution;
    private javax.swing.JButton jbViewVOHistory;
    private javax.swing.JLabel jlAttachedWorkitems;
    private javax.swing.JLabel jlAvailableWorkitems;
    private javax.swing.JLabel jlVersionedObject;
    private javax.swing.JLabel jlVersionedObjects;
    private javax.swing.JMenuItem jmiLogin;
    private javax.swing.JMenuItem jmiManageUser;
    private javax.swing.JMenuItem jmiOpenProduct;
    private javax.swing.JMenuItem jmiPermitions;
    private javax.swing.JPanel jpCommands;
    private javax.swing.JPanel jpVersionedObjects;
    private javax.swing.JPanel jpWorkItems;
    private javax.swing.JPanel jpWorkspaces;
    private javax.swing.JScrollPane jspAttachedWorkItems;
    private javax.swing.JScrollPane jspAvailableWorkItems;
    private javax.swing.JScrollPane jspVODatum;
    private javax.swing.JScrollPane jspVersionedObjects;
    private javax.swing.JTree jtAttachedWorkItems;
    private javax.swing.JTree jtAvailableWorkItems;
    private javax.swing.JTree jtVOs;
    private javax.swing.JTextArea jtaVODatum;
    private javax.swing.JTextField jtfVOName;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu usersMenu;
    // End of variables declaration//GEN-END:variables
    //private final Timer messageTimer;
    //private final Timer busyIconTimer;
    //private final Icon idleIcon;
    //private final Icon[] busyIcons = new Icon[15];
    //private int busyIconIndex = 0;
    private JDialog aboutBox;
    private OpenWorkspace openProduct;

    private void loadWorkItems() {
        try {
            CommandFactory cf = new CommandFactory();
            ICommand cmd = cf.createCommand(CommandFactory.CmdCode.GET_WORK_ITEM_LIST);

            Object res = cmd.doRequest();
            if (res != null) {
                displayWorkitems();
            }
        } catch (JSONException ex) {
            Logger.getLogger(DesktopApplication1View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void displayWorkitems() {
        try {
            BuildWorkitemTree(wiAttachedRoot, workEnvironment.getAttachedWorkItems());
            BuildWorkitemTree(wiAvailableRoot, workEnvironment.getAvailableWorkItems());

            ((DefaultTreeModel) jtAttachedWorkItems.getModel()).reload();
            ((DefaultTreeModel) jtAvailableWorkItems.getModel()).reload();
        } catch (Exception ex) {
            ex.printStackTrace(System.err);
        }
    }

    private void BuildWorkitemTree(DefaultMutableTreeNode Root, JSONArray treeElements) throws JSONException {
        int pr_len = treeElements.length();
        Root.removeAllChildren();
        JSONObject tmpWI;
        DefaultMutableTreeNode tmpNode, tmpNode2 = null;
        Map wsMap = new HashMap();
        for (int i = 0; i < pr_len; i++) {
            tmpWI = (JSONObject) treeElements.get(i);
            workitemInfo wiInfo = new workitemInfo(tmpWI.getString("name"), tmpWI.getInt("wi_id"), i);
            int constructs = tmpWI.getInt("constructs");
            if (constructs == 0) {
                tmpNode = new DefaultMutableTreeNode(wiInfo);
                Root.add(tmpNode);
                wsMap.put(wiInfo.getWi_id(), tmpNode);
            } else {
                tmpNode = new DefaultMutableTreeNode(wiInfo);
                tmpNode2 = (DefaultMutableTreeNode) wsMap.get(constructs);
                tmpNode2.add(tmpNode);
                wsMap.put(wiInfo.getWi_id(), tmpNode);
            }
        }
    }

    private void loadVersionedObjects() {
        try {
            //WorkEnvironment we = WorkEnvironment.getWorkEnvironment();
            CommandFactory cf = new CommandFactory();
            ICommand cmd = cf.createCommand(CommandFactory.CmdCode.GET_VERSIONED_OBJECT_LIST);

            JSONArray vo_ls = (JSONArray) cmd.doRequest();
            workEnvironment.setVersionedObject_ls(vo_ls);
            if (vo_ls != null) {
                displayVersionedObjectsTree();
            }
        } catch (JSONException ex) {
            Logger.getLogger(DesktopApplication1View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void displayVersionedObjectsTree() {
        try {
            //WorkEnvironment we = WorkEnvironment.getWorkEnvironment();
            JSONArray vo_ls = workEnvironment.getVersionedObject_ls();

            voRoot.removeAllChildren();
            int pr_len = vo_ls.length();
            JSONObject tmpVO;
            DefaultMutableTreeNode tmpNode, tmpNode2 = null;
            String val;
            Map wsMap = new HashMap();
            for (int i = 0; i < pr_len; i++) {
                tmpVO = (JSONObject) vo_ls.get(i);
                val = tmpVO.getString("vp_name") + " - " + workEnvironment.getVisibilityVectorString(tmpVO.getInt("v_vector"));
                voInfo voInfo = new voInfo(val, tmpVO.getInt("vo_id"), i);

                int constructs = tmpVO.getInt("constructs");
                if (constructs == 0) {
                    tmpNode = new DefaultMutableTreeNode(voInfo);
                    voRoot.add(tmpNode);
                    wsMap.put(voInfo.getVo_id(), tmpNode);
                } else {
                    tmpNode = new DefaultMutableTreeNode(voInfo);
                    tmpNode2 = (DefaultMutableTreeNode) wsMap.get(constructs);
                    tmpNode2.add(tmpNode);
                    wsMap.put(voInfo.getVo_id(), tmpNode);
                }
            }
            ((DefaultTreeModel) jtVOs.getModel()).reload();
        } catch (JSONException ex) {
            Logger.getLogger(DesktopApplication1View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

//    private void attachWorkItem() {
//        try {
//            JSONConnection jc = new JSONConnection();
//            Map params = new HashMap();
//            JSONArray notAttached = workEnvironment.getAvailableWorkItems();
//            JSONObject wi = (JSONObject) notAttached.get(jlstNotAttachedWorkitems.getSelectedIndex());
//            params.put("wi_id", Integer.parseInt(wi.get("wi_id").toString()));
//            params.put("ws_id", workEnvironment.getCurrentWs());
//            jc.prepareJSONRequest("attachWorkItem", params, uid);
//            JSONObject jResponce = jc.doRequest(null);
//            JSONObject err = jResponce.getJSONObject("error");
//            workEnvironment.setVersionedObject_ls(jResponce.getJSONArray("result"));
//            int code = err.getInt("code");
//            if (code != 0) {
//                System.err.println("JSON ERROR loadReleases - code:" + code + "; message:" + err.get("message").toString());
//            }
//
//        } catch (JSONException ex) {
//            Logger.getLogger(DesktopApplication1View.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
//
//    private void detachWorkItem() {
//        try {
//            JSONConnection jc = new JSONConnection();
//            Map params = new HashMap();
//            JSONArray notAttached = workEnvironment.getAttachedWorkItems();
//            JSONObject wi = (JSONObject) notAttached.get(jlstAttachedWorkitems.getSelectedIndex());
//            params.put("wi_id", Integer.parseInt(wi.get("wi_id").toString()));
//            params.put("ws_id", workEnvironment.getCurrentWs());
//            jc.prepareJSONRequest("detachWorkItem", params, uid);
//            JSONObject jResponce = jc.doRequest(null);
//            JSONObject err = jResponce.getJSONObject("error");
//            workEnvironment.setVersionedObject_ls(jResponce.getJSONArray("result"));
//            int code = err.getInt("code");
//            if (code != 0) {
//                System.err.println("JSON ERROR loadReleases - code:" + code + "; message:" + err.get("message").toString());
//            }
//
//        } catch (JSONException ex) {
//            Logger.getLogger(DesktopApplication1View.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }

    private void diplayVersionedObjectsHistory(JSONArray HistoryItems) {
        // TODO - idea - to show in a new window list of all historical changes of VO - source, target, time of version, user initiated the change, work item of the change
    }

    private void refreshWIButtons(boolean b) {
        jbAttachWI.setEnabled(b);
        jbDetachWI.setEnabled(b);
    }

    private void clearVOData() {
        jtfVOName.setText("");
        jtaVODatum.setText("");
        jbPublishVO.setEnabled(false);
        jbPutBackVO.setEnabled(false);
        jbSaveVO.setEnabled(false);
        jbViewVODistribution.setEnabled(false);
        jbViewVOHistory.setEnabled(false);
        jbChangeVOHat.setEnabled(false);
        jbCreateWI.setEnabled(false);
    }

    private void displayVOdata() {
        try {
            //WorkEnvironment we = WorkEnvironment.getWorkEnvironment();
            JSONObject vo = workEnvironment.getCurrentVersionedObject();
            jtfVOName.setText(vo.getString("vp_name"));
            jtaVODatum.setText(vo.getString("vp_datum"));
            jbPublishVO.setEnabled(workEnvironment.isLocalCurrentVersionedObject());
            jbPutBackVO.setEnabled(workEnvironment.isPutBackableCurrentVersionedObject());
            jbSaveVO.setEnabled(false);
            jbViewVODistribution.setEnabled(true);
            jbViewVOHistory.setEnabled(true);
            jbChangeVOHat.setEnabled(true);
            jbCreateWI.setEnabled(true);
        } catch (JSONException ex) {
            Logger.getLogger(DesktopApplication1View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
