REM INSERTING into VERSIONED_PRIMITIVE
Insert into VERSIONED_PRIMITIVE (VO_ID,VP_ID,OBJECT_NAME) values (1,1,'general workitem');
Insert into VERSIONED_PRIMITIVE (VO_ID,VP_ID,OBJECT_NAME) values (2,1,'O1.v1');
Insert into VERSIONED_PRIMITIVE (VO_ID,VP_ID,OBJECT_NAME) values (2,2,'O1.v2');
Insert into VERSIONED_PRIMITIVE (VO_ID,VP_ID,OBJECT_NAME) values (2,3,'O1.v3');
Insert into VERSIONED_PRIMITIVE (VO_ID,VP_ID,OBJECT_NAME) values (2,4,'O1.v4');
Insert into VERSIONED_PRIMITIVE (VO_ID,VP_ID,OBJECT_NAME) values (2,5,'O1.v5');
