REM INSERTING into WORKSPACE
Insert into WORKSPACE (WS_ID,WS_NAME,RELEASE_ID,ANCESTOR_WS_ID,USER_ID) values (1,'master workspace',1,null,null);
Insert into WORKSPACE (WS_ID,WS_NAME,RELEASE_ID,ANCESTOR_WS_ID,USER_ID) values (2,'A1',1,1,null);
Insert into WORKSPACE (WS_ID,WS_NAME,RELEASE_ID,ANCESTOR_WS_ID,USER_ID) values (3,'B1',1,1,null);
Insert into WORKSPACE (WS_ID,WS_NAME,RELEASE_ID,ANCESTOR_WS_ID,USER_ID) values (4,'A1.1',1,2,null);
Insert into WORKSPACE (WS_ID,WS_NAME,RELEASE_ID,ANCESTOR_WS_ID,USER_ID) values (5,'B1.1',1,3,null);
Insert into WORKSPACE (WS_ID,WS_NAME,RELEASE_ID,ANCESTOR_WS_ID,USER_ID) values (6,'B1.2',1,3,null);
