REM INSERTING into CAUSE
Insert into CAUSE (CAUSE_VO_ID,CAUSE_VP_ID,VERSION_ARC_ID) values (1,1,1);
Insert into CAUSE (CAUSE_VO_ID,CAUSE_VP_ID,VERSION_ARC_ID) values (1,1,2);
Insert into CAUSE (CAUSE_VO_ID,CAUSE_VP_ID,VERSION_ARC_ID) values (1,1,3);
Insert into CAUSE (CAUSE_VO_ID,CAUSE_VP_ID,VERSION_ARC_ID) values (1,1,4);
Insert into CAUSE (CAUSE_VO_ID,CAUSE_VP_ID,VERSION_ARC_ID) values (1,1,5);
